# Generated by Django 5.2.5 on 2025-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempentries',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
