# Generated by Django 5.2.5 on 2025-11-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_alter_tempentries_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.IntegerField(max_length=7)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_linkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products')),
            ],
        ),
    ]
