# Generated by Django 5.2.5 on 2025-11-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_category',
            old_name='category',
            new_name='category_name',
        ),
    ]
