# Generated by Django 5.2.5 on 2025-11-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_rename_category_product_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='product_itemno',
        ),
    ]
