# Generated by Django 5.2.5 on 2025-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_salesentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesentries',
            name='invoice_ref',
            field=models.IntegerField(),
        ),
    ]
