# Generated by Django 5.2.5 on 2025-11-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_rename_product_id_products_product_itemno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(max_length=100)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('itemnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products')),
            ],
        ),
    ]
