# Generated by Django 5.2.5 on 2025-11-03 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_tempentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempentries',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempentries',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
