# Generated by Django 5.2.5 on 2025-09-27 04:09

import app_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnumber', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storecategory', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_store.models.store_upload_path)),
            ],
        ),
    ]
