# Generated by Django 5.2.5 on 2025-11-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='sal_empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='app_employees.employee'),
        ),
    ]
