# Generated by Django 5.2.5 on 2025-10-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deptname',
        ),
    ]
