# Generated by Django 5.2.5 on 2025-11-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0002_alter_employeesalary_sal_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='sal_empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary', to='app_employees.employee', unique=True),
        ),
    ]
