# Generated by Django 5.2.5 on 2025-10-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0003_remove_employee_department_employee_deptname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deptname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_employees.department'),
            preserve_default=False,
        ),
    ]
