# Generated by Django 5.2.5 on 2025-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0004_alter_employeesalary_sal_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='test@1.com', max_length=254, unique=True),
        ),
    ]
