# Generated by Django 5.2.5 on 2025-11-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_alter_nextdatacontrol_nextserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextdatacontrol',
            name='nextserial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
