# Generated by Django 5.2.5 on 2025-12-04 00:32

import app_condo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_img', models.ImageField(blank=True, null=True, upload_to='stmt_upload_path')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CondoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_img', models.ImageField(blank=True, null=True, upload_to=app_condo.models.pymt_upload_path)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('bill_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_condo.condobill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condo_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
