# Generated by Django 5.2.5 on 2025-11-21 00:50

import app_condo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('statement_amount', models.FloatField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('img_stmt', models.ImageField(blank=True, null=True, upload_to=app_condo.models.stmt_upload_path)),
                ('img_pymt', models.ImageField(blank=True, null=True, upload_to=app_condo.models.pymt_upload_path)),
            ],
        ),
    ]
