# Generated by Django 5.2.5 on 2025-09-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('statement_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
