# Generated by Django 5.2.5 on 2025-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_condo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condobill',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condobill',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condobill',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
