# Generated by Django 5.2.5 on 2025-09-29 03:40

import app_condo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_condo', '0002_condobill_payment_amount_condobill_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condobill',
            name='img_pymt',
            field=models.ImageField(blank=True, null=True, upload_to=app_condo.models.pymt_upload_path),
        ),
        migrations.AddField(
            model_name='condobill',
            name='img_stmt',
            field=models.ImageField(blank=True, null=True, upload_to=app_condo.models.stmt_upload_path),
        ),
    ]
